apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-test
  template:
    metadata:
      labels:
        app: pvc-test
    spec:
      containers:
      - name: app
        image: nginx
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: test-storage
      volumes:
      - name: test-storage
        persistentVolumeClaim:
          claimName: test-pvc

---
# Persistent Volume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 2Gi   
  accessModes:
    - ReadWriteMany   
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

---
# Persistent Volume Claim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce   
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi   
