apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-app
  namespace: sre-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-app
  template:
    metadata:
      labels:
        app: cpu-app
    spec:
      containers:
      - name: cpu-app-container
        image: python:3.11-slim
        command: ["python", "-u", "-m", "http.server", "8080"]  
        resources:
          requests:
            cpu: "10m"   
          limits:
            cpu: "200m"   
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
        ports:
        - containerPort: 8080
