apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat-agent 
    spec:
      serviceAccountName: filebeat 
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.17.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e"
        ]
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers 
        - name: config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/pods 
      - name: config
        configMap:
          name: filebeat-conf 
