---
apiVersion: v1
kind: Namespace
metadata:
  name: sre-lab
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: sre-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: test-sre-lab   
        - name: POSTGRES_DB
          value: testdb
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: sre-lab
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: sre-lab
type: Opaque
data:
  DB_USER: YWRtaW4=                 
  DB_PASSWORD: aGZqZ2FzYmNzaHlmcmc= 
  DB_NAME: dGVzdGRi                 
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ== 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: sre-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
      - name: app-container
        image: postgres:14
        command: ["sh", "-c"]
        args:
          - |
            echo "Starting App"
            if PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1;" > /dev/null 2>/tmp/pgerr; then
              echo "DB OK"
              while true; do sleep 3600; done
            else
              echo "Startup failed"
              exit 1
            fi
        envFrom:
        - secretRef:
            name: app-secret
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c "SELECT 1;"
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
