apiVersion: v1
kind: Namespace
metadata:
  name: sre-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sre-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend   
    spec:
      containers:
        - name: backend
          image: hashicorp/http-echo
          args:
            - "-text=Hello from backend"
          ports:
            - containerPort: 5678  
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 1
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sre-lab
spec:
  selector:
    app: app-backend  
  ports:
    - port: 8080        
      targetPort: 5678  
---
apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: sre-lab
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
