apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-sales-report
spec:
  schedule: "0 2 */2 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: report-generator
            image: company/report-generator:1.2.3
            env:
            - name: S3_BUCKET
              value: "daily-reports"
            - name: REPORT_PATH
              value: "/tmp/report.csv"
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          restartPolicy: OnFailure
