apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_MODE: "prod"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-test
  template:
    metadata:
      labels:
        app: config-test
    spec:
      containers:
      - name: test
        image: busybox
        command: ["sh", "-c", "echo Mode: $APP_MODE && sleep 3600"]
        
