apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: production
data:
  PAYMENT_API_KEY: "xvshgfetfrgdehwkjekfg"
  PAYMENT_TIMEOUT: "30"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-container
          image: nginx:alpine
          ports:
            - containerPort: 80
